In [5]:
import numpy as np
#Nutrient replacement for 3 crops (n, p ,k  kg/ha)
#rows: crops (wheat, corn,rice)
#column: Nutrients (n, p , k)
nutrients_needs=np.array([
      [120,60,80],
      [150,75,100],
      [100,50,70]
  ])
#available fertilizer composition (percentage of n, p , k)
#rows: fertilizer type
#column: nutrient content
fertilizer_composition=np.array([
      [0.20,0.10,0.15],
      [0.15,0.20,0.10],
      [0.10,0.15,0.25]
  ])
print("nutrient requirement(kg/ha):")
print("nutrients_needs")
print("\nfertilizer composition(%):")
print("fertilizer_composition")

#matrix transpose example
print("\nTransposed nutrients needs(nutrients*crops):")
print("nutrients_needs:T")

#calculate fertilizer amount
total_nutrients_per_crop=np.sum(nutrients_needs, axis=1)
print(f"\ntotal nutrients needed per crop;{total_nutrients_per_crop}kg/ha")

#matrix multiplication : calculate total nutrient delivery
fertilizer_application=np.array([100,100,100])
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f"\nNutrients from 100kg each fertilizer:{nutrients_delivered}")

#calculate determinant(for checking if matrix is invertible)
det=np.linalg.det(fertilizer_composition)
print(f"\nDeterminant of fertilizer matrix: {det:.6f}")

#identity matrix example
scaling=np.eye(3)*1.1
enhanced_needs=np.dot(nutrients_needs, scaling)
print("\nEnhanced nutrient needs(10% increase):")
print(enhanced_needs)


nutrient requirement(kg/ha):
nutrients_needs

fertilizer composition(%):
fertilizer_composition

Transposed nutrients needs(nutrients*crops):
nutrients_needs:T

total nutrients needed per crop;[260 325 220]kg/ha

Nutrients from 100kg each fertilizer:[45. 45. 50.]

Determinant of fertilizer matrix: 0.004625

Enhanced nutrient needs(10% increase):
[[132.   66.   88. ]
 [165.   82.5 110. ]
 [110.   55.   77. ]]


In [6]:
import numpy as np
#creat a  10*5 array with values from 0 to 49
a=np.arange(50).reshape(10,5)
print("original array (10*5):\n",a)
print(a[:])
print(a[:,0])
print(a[:,1])
selected_rows=a[a[:,0]>20]
print("\nRows where first feature>20:\n",selected_rows)

original array (10*5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[ 0  5 10 15 20 25 30 35 40 45]
[ 1  6 11 16 21 26 31 36 41 46]

Rows where first feature>20:
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [9]:
import numpy as np
#rainfall data(mm) over 12 months
rainfall=np.array([45,52,68,120,180,220,195,160,110,75,58,40])
yields=np.array([2.1,3.2,5.6,2.3,5.6,4.3,9.2,5.6,2.6,4.6,6.5,8.6])
print("===RAINFALL STATISTICS===")
print(f"mean:{np.mean(rainfall):.2f}mm")
print("fmedian:{np.median(rainfall):.2f}mm")
print(f"std dev:{np.std(rainfall):.2f}mm")
print(f"variance:{np.var(rainfall):.2f}")
print(f"min:{np.min(rainfall)}mm(Month{np.argmin(rainfall)+1})")
print(f"max:{np.max(rainfall)}mm(Month{np.argmax(rainfall)+1})")
print(f"Range:{np.ptp(rainfall)}mm")



print("\n===YIELD STATISTICS===")
print(f"Mean:{np.mean(yields):.2f}tons/ha")
print(f"Median:{np.median(yields):.2f}tons/ha")
print(f"Std Dev:{np.std(yields):.2f}tons/ha")


print("\n===PERCENTILES===")
percentiles=[25,50,75,90]
rainfall_percentiles=np.percentile(rainfall,percentiles)
for p,val in zip(percentiles,rainfall_percentiles):
  print(f"{p}th percentiles rainfall:{val:.2f}mm")


print("\n===CORRELATION ANALYSIS===")
correlation_matrix=np.corrcoef(rainfall,yields)
correlation=correlation_matrix[0,1]
print(f"Rainfall-Yield Correlation:{correlation:.4f}")
print("interpretation: Strong positive correlation"if correlation>0.7 else "Moderate correlation" if correlation >0.4 else "Weak correlation")


print("\n===CUMULATIVE RAINFALL===")
cumulative=np.cumsum(rainfall)
print("Month\tRainfall\tCumulative")
for month,(rain,cum)in enumerate(zip(rainfall,cumulative),1):
  print(f"{month}\t{rain}\t\t{cum}")

===RAINFALL STATISTICS===
mean:110.25mm
fmedian:{np.median(rainfall):.2f}mm
std dev:61.24mm
variance:3750.52
min:40mm(Month12)
max:220mm(Month6)
Range:180mm

===YIELD STATISTICS===
Mean:5.02tons/ha
Median:5.10tons/ha
Std Dev:2.22tons/ha

===PERCENTILES===
25th percentiles rainfall:56.50mm
50th percentiles rainfall:92.50mm
75th percentiles rainfall:165.00mm
90th percentiles rainfall:193.50mm

===CORRELATION ANALYSIS===
Rainfall-Yield Correlation:0.1694
Weak correlation

===CUMULATIVE RAINFALL===
Month	Rainfall	Cumulative
1	45		45
2	52		97
3	68		165
4	120		285
5	180		465
6	220		685
7	195		880
8	160		1040
9	110		1150
10	75		1225
11	58		1283
12	40		1323
